""" Draw performance evaluation result.
dataset generated by:
seq 50 50 3000 | xargs -t -P 8 -I{} pipenv run python generator.py --count {} --point 30000 --vmin 6 --vmax 6 --output './dataset/polygon_input_c'{}'_v6.txt'
performance evaluated by:
ls dataset | sort -n -t c -k 2 | xargs -t -L 1 -I{} ./sat.out -i ./dataset/{} -o polygon_output.txt
ls dataset | sort -n -t c -k 2 | xargs -t -L 1 -I{} ./sat.out -i ./dataset/{} -o polygon_output.txt -g
"""
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
from matplotlib import pyplot as plt

CPU_TIME = """./sat.out -i ./dataset/polygon_input_c50_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.001356 sec
./sat.out -i ./dataset/polygon_input_c100_v6.txt -o polygon_output.txt
CPU Execution Time elapsed 0.005332 sec
./sat.out -i ./dataset/polygon_input_c150_v6.txt -o polygon_output.txt
CPU Execution Time elapsed 0.016695 sec
./sat.out -i ./dataset/polygon_input_c200_v6.txt -o polygon_output.txt
CPU Execution Time elapsed 0.020711 sec
./sat.out -i ./dataset/polygon_input_c250_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.046008 sec
./sat.out -i ./dataset/polygon_input_c300_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.046329 sec
./sat.out -i ./dataset/polygon_input_c350_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.062508 sec
./sat.out -i ./dataset/polygon_input_c400_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.081325 sec
./sat.out -i ./dataset/polygon_input_c450_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.103144 sec
./sat.out -i ./dataset/polygon_input_c500_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.129491 sec
./sat.out -i ./dataset/polygon_input_c550_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.156452 sec
./sat.out -i ./dataset/polygon_input_c600_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.183409 sec
./sat.out -i ./dataset/polygon_input_c650_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.235151 sec
./sat.out -i ./dataset/polygon_input_c700_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.251301 sec
./sat.out -i ./dataset/polygon_input_c750_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.286349 sec
./sat.out -i ./dataset/polygon_input_c800_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.327241 sec
./sat.out -i ./dataset/polygon_input_c850_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.372927 sec
./sat.out -i ./dataset/polygon_input_c900_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.412731 sec
./sat.out -i ./dataset/polygon_input_c950_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.468621 sec
./sat.out -i ./dataset/polygon_input_c1000_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.542758 sec
./sat.out -i ./dataset/polygon_input_c1050_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.555405 sec
./sat.out -i ./dataset/polygon_input_c1100_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.617404 sec
./sat.out -i ./dataset/polygon_input_c1150_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.680003 sec
./sat.out -i ./dataset/polygon_input_c1200_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.723029 sec
./sat.out -i ./dataset/polygon_input_c1250_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.792855 sec
./sat.out -i ./dataset/polygon_input_c1300_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.853474 sec
./sat.out -i ./dataset/polygon_input_c1350_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 0.927661 sec
./sat.out -i ./dataset/polygon_input_c1400_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.039736 sec
./sat.out -i ./dataset/polygon_input_c1450_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.094044 sec
./sat.out -i ./dataset/polygon_input_c1500_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.178395 sec
./sat.out -i ./dataset/polygon_input_c1550_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.230562 sec
./sat.out -i ./dataset/polygon_input_c1600_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.304440 sec
./sat.out -i ./dataset/polygon_input_c1650_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.388856 sec
./sat.out -i ./dataset/polygon_input_c1700_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.484913 sec
./sat.out -i ./dataset/polygon_input_c1750_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.682160 sec
./sat.out -i ./dataset/polygon_input_c1800_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.653176 sec
./sat.out -i ./dataset/polygon_input_c1850_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.823238 sec
./sat.out -i ./dataset/polygon_input_c1900_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.884536 sec
./sat.out -i ./dataset/polygon_input_c1950_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 1.950227 sec
./sat.out -i ./dataset/polygon_input_c2000_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.055459 sec
./sat.out -i ./dataset/polygon_input_c2050_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.149452 sec
./sat.out -i ./dataset/polygon_input_c2100_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.230151 sec
./sat.out -i ./dataset/polygon_input_c2150_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.358670 sec
./sat.out -i ./dataset/polygon_input_c2200_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.612397 sec
./sat.out -i ./dataset/polygon_input_c2250_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.738645 sec
./sat.out -i ./dataset/polygon_input_c2300_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.942132 sec
./sat.out -i ./dataset/polygon_input_c2350_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.953905 sec
./sat.out -i ./dataset/polygon_input_c2400_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 2.985166 sec
./sat.out -i ./dataset/polygon_input_c2450_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 3.113888 sec
./sat.out -i ./dataset/polygon_input_c2500_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 3.117471 sec
./sat.out -i ./dataset/polygon_input_c2550_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 3.278429 sec
./sat.out -i ./dataset/polygon_input_c2600_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 3.453261 sec
./sat.out -i ./dataset/polygon_input_c2650_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 3.603989 sec
./sat.out -i ./dataset/polygon_input_c2700_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 3.759412 sec
./sat.out -i ./dataset/polygon_input_c2750_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 3.921768 sec
./sat.out -i ./dataset/polygon_input_c2800_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 4.092872 sec
./sat.out -i ./dataset/polygon_input_c2850_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 4.383147 sec
./sat.out -i ./dataset/polygon_input_c2900_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 4.637649 sec
./sat.out -i ./dataset/polygon_input_c2950_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 4.532162 sec
./sat.out -i ./dataset/polygon_input_c3000_v6.txt -o polygon_output.txt 
CPU Execution Time elapsed 4.928526 sec"""

GPU_TIME = """./sat.out -i ./dataset/polygon_input_c50_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.112024 sec
./sat.out -i ./dataset/polygon_input_c100_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.111698 sec
./sat.out -i ./dataset/polygon_input_c150_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.110913 sec
./sat.out -i ./dataset/polygon_input_c200_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.115929 sec
./sat.out -i ./dataset/polygon_input_c250_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.116436 sec
./sat.out -i ./dataset/polygon_input_c300_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.116931 sec
./sat.out -i ./dataset/polygon_input_c350_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.114709 sec
./sat.out -i ./dataset/polygon_input_c400_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.116099 sec
./sat.out -i ./dataset/polygon_input_c450_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.119163 sec
./sat.out -i ./dataset/polygon_input_c500_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.119552 sec
./sat.out -i ./dataset/polygon_input_c550_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.122334 sec
./sat.out -i ./dataset/polygon_input_c600_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.126179 sec
./sat.out -i ./dataset/polygon_input_c650_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.129758 sec
./sat.out -i ./dataset/polygon_input_c700_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.134032 sec
./sat.out -i ./dataset/polygon_input_c750_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.136931 sec
./sat.out -i ./dataset/polygon_input_c800_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.140626 sec
./sat.out -i ./dataset/polygon_input_c850_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.148571 sec
./sat.out -i ./dataset/polygon_input_c900_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.149172 sec
./sat.out -i ./dataset/polygon_input_c950_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.159218 sec
./sat.out -i ./dataset/polygon_input_c1000_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.163656 sec
./sat.out -i ./dataset/polygon_input_c1050_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.173207 sec
./sat.out -i ./dataset/polygon_input_c1100_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.181143 sec
./sat.out -i ./dataset/polygon_input_c1150_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.190883 sec
./sat.out -i ./dataset/polygon_input_c1200_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.195911 sec
./sat.out -i ./dataset/polygon_input_c1250_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.210824 sec
./sat.out -i ./dataset/polygon_input_c1300_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.218925 sec
./sat.out -i ./dataset/polygon_input_c1350_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.236001 sec
./sat.out -i ./dataset/polygon_input_c1400_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.242758 sec
./sat.out -i ./dataset/polygon_input_c1450_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.261369 sec
./sat.out -i ./dataset/polygon_input_c1500_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.270559 sec
./sat.out -i ./dataset/polygon_input_c1550_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.286367 sec
./sat.out -i ./dataset/polygon_input_c1600_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.300566 sec
./sat.out -i ./dataset/polygon_input_c1650_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.327905 sec
./sat.out -i ./dataset/polygon_input_c1700_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.341701 sec
./sat.out -i ./dataset/polygon_input_c1750_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.364511 sec
./sat.out -i ./dataset/polygon_input_c1800_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.373299 sec
./sat.out -i ./dataset/polygon_input_c1850_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.407144 sec
./sat.out -i ./dataset/polygon_input_c1900_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.416850 sec
./sat.out -i ./dataset/polygon_input_c1950_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.449723 sec
./sat.out -i ./dataset/polygon_input_c2000_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.444125 sec
./sat.out -i ./dataset/polygon_input_c2050_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.487265 sec
./sat.out -i ./dataset/polygon_input_c2100_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.507432 sec
./sat.out -i ./dataset/polygon_input_c2150_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.560007 sec
./sat.out -i ./dataset/polygon_input_c2200_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.577328 sec
./sat.out -i ./dataset/polygon_input_c2250_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.612299 sec
./sat.out -i ./dataset/polygon_input_c2300_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.635890 sec
./sat.out -i ./dataset/polygon_input_c2350_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.653504 sec
./sat.out -i ./dataset/polygon_input_c2400_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.667452 sec
./sat.out -i ./dataset/polygon_input_c2450_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.735060 sec
./sat.out -i ./dataset/polygon_input_c2500_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.744328 sec
./sat.out -i ./dataset/polygon_input_c2550_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.800200 sec
./sat.out -i ./dataset/polygon_input_c2600_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.814988 sec
./sat.out -i ./dataset/polygon_input_c2650_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.911257 sec
./sat.out -i ./dataset/polygon_input_c2700_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.908402 sec
./sat.out -i ./dataset/polygon_input_c2750_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.966827 sec
./sat.out -i ./dataset/polygon_input_c2800_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 0.970095 sec
./sat.out -i ./dataset/polygon_input_c2850_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 1.059748 sec
./sat.out -i ./dataset/polygon_input_c2900_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 1.089647 sec
./sat.out -i ./dataset/polygon_input_c2950_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 1.163228 sec
./sat.out -i ./dataset/polygon_input_c3000_v6.txt -o polygon_output_gpu.txt -g 
GPU Execution Time elapsed 1.147439 sec"""

polygon_n_list = re.findall(r'polygon_input_c(\d+)_v6.txt', CPU_TIME)
polygon_n_list = [int(i) for i in polygon_n_list]

cpu_time_list = re.findall(r'elapsed (.*?) sec', CPU_TIME)
cpu_time_list = [float(i) for i in cpu_time_list]

gpu_time_list = re.findall(r'elapsed (.*?) sec', GPU_TIME)
gpu_time_list = [float(i) for i in gpu_time_list]

assert len(polygon_n_list) == len(cpu_time_list) == len(gpu_time_list)

# efficiency

# speedup ratio
Sp = [T1/Tp for T1, Tp in zip(cpu_time_list, gpu_time_list)]

print(polygon_n_list)
print(cpu_time_list)
print(gpu_time_list)

print(Sp)

plt.title('performance evaluation of vertices in [3, 6]')
plt.xlabel('number of polygons')
plt.ylabel('running time(sec)')
plt.plot(polygon_n_list, cpu_time_list, label="CPU")
plt.plot(polygon_n_list, gpu_time_list, label="GPU")
plt.legend()
plt.show()

plt.title('Speedup ratio')
plt.xlabel('number of polygons')
plt.ylabel('Speedup ratio')
plt.axhline(1.0, linestyle='--')
below1 = [i for i in Sp if i < 1.0]
above1 = [i for i in Sp if i >= 1.0]
plt.plot(polygon_n_list[:len(below1)], below1, 'r')
plt.plot(polygon_n_list[len(below1):], above1, 'g')
plt.show()